# Accessibility Scanner Configuration
# This file defines default settings and thresholds for accessibility scanning

# Default scan settings
default:
  target_url: "https://ncaa-d1-softball.netlify.app/"
  standards: "WCAG2AA"  # WCAG2A, WCAG2AA, WCAG2AAA, Section508, EN301549
  tools: "axe,pa11y,lighthouse,playwright"
  report_dir: "accessibility-reports"
  timeout: 30000
  retries: 2
  parallel: true

# Quality gates and thresholds - Government compliance standards (WCAG 2.1 AA)
thresholds:
  max_critical_violations: 0      # Government standard: Zero critical violations allowed
  max_serious_violations: 0       # Government standard: Zero serious violations for AA compliance  
  max_moderate_violations: 2      # Government standard: Minimal moderate violations allowed
  max_minor_violations: 5         # Government standard: Limited minor violations acceptable
  min_lighthouse_score: 95        # Government standard: High accessibility score required
  max_pa11y_issues: 0            # Government standard: Zero Pa11y issues for full compliance
  max_playwright_violations: 0    # Government standard: Zero end-to-end accessibility violations

# Tool-specific configurations - Enhanced for WCAG 2.1 government compliance
tools:
  axe:
    standards: ["wcag2a", "wcag2aa", "wcag21aa", "wcag21a"]  # Full WCAG 2.1 Level A & AA coverage
    chrome_options: ["no-sandbox", "disable-dev-shm-usage"]
    fail_on_violations: true                                  # Strict enforcement for government compliance
    include_experimental: false                               # Only use stable rules for compliance
    best_practices: true                                      # Include accessibility best practices
    
  pa11y:
    standard: "WCAG2AA"                                      # WCAG 2.1 Level AA standard
    chrome_options: ["no-sandbox", "disable-dev-shm-usage", "disable-gpu", "headless"]
    reporters: ["json", "html", "csv"]
    include_warnings: true                                    # Include all warnings for government review
    include_notices: true                                     # Include notices for comprehensive reporting
    ignore_rules: []                                         # No ignored rules for full government compliance
    timeout: 45000                                           # Extended timeout for thorough analysis
    
  lighthouse:
    form_factors: ["desktop", "mobile"]                      # Test both desktop and mobile compliance
    categories: ["accessibility"]
    chrome_flags: ["headless", "no-sandbox", "disable-dev-shm-usage"]
    settings:
      only_categories: ["accessibility"]                     # Focus on accessibility audit
      skip_audits: []                                        # No skipped audits for complete compliance
    
  playwright:
    browsers: ["chromium"]                                   # Primary browser for government testing
    workers: 1                                               # Single worker for consistent results
    test_file: "tests/accessibility/accessibility.spec.js"
    timeout: 60000                                           # Extended timeout for comprehensive testing
    screenshot_on_failure: true                              # Document failures for compliance reports

# Multi-standard support - Enhanced for government compliance
standards:
  WCAG21A:
    description: "Web Content Accessibility Guidelines 2.1 Level A - Government Compliance"
    tags: ["wcag2a", "wcag21a"]
    government_approved: true
    
  WCAG21AA:
    description: "Web Content Accessibility Guidelines 2.1 Level AA - Government Standard"
    tags: ["wcag2a", "wcag2aa", "wcag21aa"]
    government_approved: true
    required_for_compliance: true
    
  WCAG21AAA:
    description: "Web Content Accessibility Guidelines 2.1 Level AAA - Enhanced Government Compliance"
    tags: ["wcag2a", "wcag2aa", "wcag2aaa", "wcag21aaa"]
    government_approved: true
    enhanced_compliance: true
    
  Section508:
    description: "Section 508 (US Federal Accessibility) - Government Requirement"
    tags: ["section508", "wcag2a", "wcag2aa"]
    government_approved: true
    federal_requirement: true
    
  EN301549:
    description: "EN 301 549 (European Accessibility Standard) - International Government Standard"
    tags: ["en301549", "wcag2a", "wcag2aa"]
    government_approved: true
    international_standard: true

# WCAG 2.1 Compliance Documentation Requirements
wcag21_compliance:
  required_level: "AA"                    # Government standard compliance level
  document_conformance: true              # Generate conformance documentation
  accessibility_statement_required: true # Public accessibility statement required
  periodic_review_months: 12             # Annual compliance review required
  user_testing_required: true           # User testing with assistive technology required
  complaint_process_documented: true     # Document accessibility complaint process

# Workflow execution settings
execution:
  parallel_tools: true           # Run tools in parallel for speed
  fail_fast: true               # Stop on first critical failure
  continue_on_error: true       # Continue other tools if one fails
  cache_tools: true             # Cache tool installations
  generate_artifacts: true      # Upload reports as artifacts
  
# Reporting and notifications - Enhanced for government compliance documentation
reporting:
  generate_dashboard: true       # Create comprehensive HTML dashboard for stakeholders
  generate_summary: true        # Create detailed markdown summary with compliance status
  generate_pr_comment: true     # Create PR comment format for code review process
  include_screenshots: true     # Include failure screenshots for documentation
  include_video: false          # Keep file size manageable for government systems
  generate_compliance_report: true    # Generate formal compliance documentation
  include_remediation_guide: true     # Include specific remediation instructions
  retention_days: 365                 # Extended retention for government audit requirements
  
  # Government compliance reporting formats
  formats: ["json", "html", "csv", "pdf"]  # Include PDF for formal documentation
  
  # Compliance documentation sections
  compliance_sections:
    - "executive_summary"         # High-level compliance status
    - "detailed_findings"         # Complete violation inventory  
    - "wcag_conformance_table"    # WCAG 2.1 conformance level documentation
    - "remediation_timeline"      # Recommended fix priorities and timeline
    - "testing_methodology"       # Documentation of testing approach
    - "accessibility_statement"   # Template for public accessibility statement
  
  # Webhook notifications for government stakeholders
  webhooks:
    slack_url: ""               # Slack webhook URL for team notifications
    teams_url: ""               # Microsoft Teams webhook URL for government teams
    discord_url: ""             # Discord webhook URL if used
    compliance_webhook: ""      # Dedicated webhook for compliance team notifications
    
# Environment-specific overrides - Government compliance standards
environments:
  development:
    target_url: "http://localhost:3000"
    thresholds:
      max_critical_violations: 2       # More lenient during development
      max_serious_violations: 5        # Allow some serious violations in dev
      max_moderate_violations: 10      # Higher tolerance for dev environment
      min_lighthouse_score: 80         # Lower threshold for development
      max_pa11y_issues: 5             # Allow some issues during development
      max_playwright_violations: 3     # Some tolerance for dev testing
      
  staging:
    target_url: "https://staging.ncaa-d1-softball.netlify.app/"
    thresholds:
      max_critical_violations: 0       # Zero critical violations in staging
      max_serious_violations: 1        # Very limited serious violations
      max_moderate_violations: 3       # Minimal moderate violations
      min_lighthouse_score: 92         # High threshold for staging
      max_pa11y_issues: 1             # Almost zero tolerance for staging
      max_playwright_violations: 1     # Minimal violations in staging
      
  production:
    target_url: "https://ncaa-d1-softball.netlify.app/"
    thresholds:
      max_critical_violations: 0       # Government standard: Zero critical violations
      max_serious_violations: 0        # Government standard: Zero serious violations
      max_moderate_violations: 0       # Government standard: Zero moderate violations for full compliance
      max_minor_violations: 2          # Government standard: Very limited minor violations
      min_lighthouse_score: 96         # Government standard: Highest accessibility score
      max_pa11y_issues: 0             # Government standard: Full compliance required
      max_playwright_violations: 0     # Government standard: Zero violations in production

# Repository-specific settings (can be overridden)
repository:
  owner: "seanmac5291"
  name: "NCAA-D1-Softball-WebApp"
  branch: "main"
  
# Governance settings - Government compliance enforcement
governance:
  require_approval: true           # Require manual approval for accessibility failures in government context
  block_merges: true              # Block PR merges on accessibility failures for compliance
  auto_create_issues: true        # Automatically create GitHub issues for compliance tracking
  assign_reviewers: []            # GitHub usernames for accessibility compliance review
  compliance_review_required: true # Additional compliance review step for government standards
  audit_trail: true               # Maintain detailed audit trail for government compliance
  legal_review_threshold: "serious" # Trigger legal review for serious+ violations

